### ISSUE TITLE
Tracking issue: changes since fork

### ISSUE THREAD

**Issue by wookayin** [wookayin/semshi#1]
# General

- Add CI (Github actions)
- Python minimum version requirement is raised to 3.6, to take advantage of python typings: see https://endoflife.date/python 
- Minor refactoring and start using type annotations

# Python Language Support

- Python 3.8: Fix broken test (11a6df5c96676280325ac0da49a8752d08f3a6ba)
- Python 3.8+: Add support for PEP-563: `from __future__ import annotations` (see #2)
- Support Python 3.11 (no major syntax changes or big feature yet)
- Python 3.12 is not yet supported, semshi v0.2.0 will give warnings on Python 3.12+

# Bug fixes: neovim remote plugin

- Avoid viewport errors when resizing vim  (11cf4e7738377298efd27d7db406c45115b5a79e)
- Avoid unknown function error: SemshiBufWipeout (52df970d21dcc1976b3842179afe17fbc9344bcf)
- Fix invalid buffer id (numirias/semshi#44)
- Fix Invalid window id error (#3)
- More useful information for `:Semshi status` (#15)
- #4

**Comment by InCogNiTo124** [comment]
Hey, thanks for the fork, I love it. Do you need any help?

**Comment by wookayin** [comment]
This is up to what we call [semshi v0.2.0](https://github.com/wookayin/semshi/releases/tag/v0.2.0). Continued support will be made (including Python 3.12) on v0.3.0 and onwards. I will no longer maintain this issue, future changes and improvements can be tracked in the [issues](https://github.com/wookayin/semshi/issues) and [releases](https://github.com/wookayin/semshi/releases).
