### ISSUE TITLE
Different highlighting for constants a.k.a. ALL_CAPS_VARIABLES

### ISSUE THREAD

**Issue by borea17** [wookayin/semshi#5]
[nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) highlights all caps variables differently, while semshi does not.

| treesitter | semshi|
| :---: | :----: |
|![image](https://user-images.githubusercontent.com/42578311/211838861-4c61d4c4-7372-40e4-ad6f-10df3fedd68c.png) |![image](https://user-images.githubusercontent.com/42578311/211839331-d7903230-44cd-4b36-b1ad-27b5a2e064a8.png)|

**Comment by wookayin** [comment]
Hi! I haven't checked the treesitter's query file for python but probably depending on whether it's ALL_CAPS or not, it would assign different semantic tokens. Semshi, however, relies on python's symbol table so does not distinguish tokens based on the literal representation. 

So this would be technically possible, by combining "GLOBAL" token and additional regex tests to define additional highlight groups (e.g. `semshiConstant`) but I'm not so sure yet what would be the best name for such groups.
