### ISSUE TITLE
LSP support / other languages

### ISSUE THREAD

**Issue by gerion0** [wookayin/semshi#6]
I find this plugin really really helpful and was asking myself if there are similar plugins for other languages, but did not find any.
Also, it seems that this plugin duplicates parts of the functionality of a language server (i.e. the detection of code semantics.).
I saw that neovim recently [has merged support](https://github.com/neovim/neovim/pull/21100) for semantic tokens which seems to go into this direction.

Do you know other plugins for other languages that do the same like semshi? What do you think of multi language support? And do you think that LSP integration helps for that?

**Comment by wookayin** [comment]
Hi, I'm not the original author of this plugin but I think the main purpose of semshi is to implement semantic-related for the Python language. It is independent and unaware of LSP, and of course LSP and semshi do many similar and overlapping things in different ways. So supporting other languages and/or LSP features will be out of the scope of this plugin.

In my opinion, ideally all the functionalities (language-agnnstic and python-specific) could be implemented under the LSP protocol, but LSP providers such as pyright and python-lsp may not have all the features needed at this point. Semshi will try to fill in those gaps for python users in neovim.
